config/routes.rb
Rails.application.routes.draw do

  get  "/" => "home#index"
  
  resources :todos

  resources :users

  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
    validates :todo_text, presence: true
    validates :due_date, presence: true
    validates :todo_text, length: { minimum: 2 }

    belongs_to :user

    def self.of_user(user)
        all.where(user_id: user.id)
    end

    def due_today?
        due_date == Date.today
    end

    def self.overdue
        all.where("due_date < ?",Date.today)
    end

    def self.duetoday
        all.where(due_date: Date.today)
    end

    def self.duelater
        all.where("due_date > ?",Date.today)
    end

    def self.completed
        all.where(completed: true)
    end
    
    def to_displayable_string
        display_status = completed ? "[X]" : "[ ]"
        display_date = due_today? ? nil : due_date
        "#{id}. #{display_status} #{todo_text} #{display_date}"
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :ensure_user_logged_in

    def ensure_user_logged_in
        unless current_user
            redirect_to "/"
        end
    end

    def current_user
        #memoization
        return @current_user if @current_user

        current_user_id = session[:current_user_id]
        if current_user_id
            @current_user = User.find(current_user_id)
        else
            nil
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    skip_before_action :ensure_user_logged_in

    def index
        if current_user
            redirect_to todos_path
        else
            render "index"
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :ensure_user_logged_in

    def new
    end

    def create
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
            session[:current_user_id] = user.id
            redirect_to "/"
        else
            flash[:error] = "Login invalid. Please retry."
            redirect_to new_sessions_path
        end
    end

    def destroy
        session[:current_user_id] = nil
        @current_user = nil
        redirect_to "/"
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    def index
        @todos = Todo.of_user(current_user)
        render "index"
    end

    def create
        todo_text = params[:todo_text_input]
        due_date = params[:due_date_input]
        new_todo = Todo.new(
            todo_text: todo_text, 
            due_date: due_date, 
            completed: false,
            user_id: current_user.id
        )
        if new_todo.save
            redirect_to todos_url
        else
            flash[:error] = new_todo.errors.full_messages.join(", ")
            redirect_to todos_url
        end
    end

    def update
        id = params[:id]
        completed = params[:completed]
        todo = Todo.of_user(current_user).find(id)
        todo.completed = completed
        todo.save!
        redirect_to todos_url
    end

    def destroy
        id = params[:id]
        todo = Todo.of_user(current_user).find(id)
        todo.delete
        redirect_to todos_url
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :ensure_user_logged_in

    def new
        render "users/new"
    end

    def create
        user = User.create!(
            first_name: params[:first_name],
            last_name: params[:last_name],
            email: params[:email],
            password: params[:password]
        )
        session[:current_user_id] = user.id
        redirect_to "/"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<section class="Home-main">
    <h1 class="Home-title">Welcome to the Todo homepage </p>

    <h3 class="Home-authenticate">
        If you are a new user, <%= link_to "sign-up here", new_user_path %> 
    </h3>

    <h3 class="Home-authenticate">
        If you are an existing user, <%= link_to "sign-in here", new_sessions_path %> 
    </h3>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManagerSaas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @current_user %>
      <p class="UserHeader">
        Welcome <%= @current_user.first_name %>
        <%= link_to "Sign-out", destroy_session_path, method: "delete" %>
      </p>
    <% end %>

    <% if flash[:error] %>
      <p class="Flash-error">
        <%= flash[:error] %>
      </p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/todos/_todo-section.html.erb
<section class="TodoSection">
    <div class="TodoSectionTitle">
        <p class="TodoSectionTitle-text"><%= section_title %></p>
        <p class="TodoSectionTitle-remainingCount"><%= todos.completed.count %>/<%= todos.count %></p>
    </div>

    <ul>
        <% todos.each do |todo| %>
            <li class="TodoItem">
                <label class="TodoItem-container">
                    <%= form_with(url: "/todos/#{todo.id}", method: "put") do %>
                        <input 
                            class="TodoItem-checkbox"
                            name = "completed" 
                            type="checkbox" <%= todo.completed ? "checked" : "" %>
                            onclick = "this.form.submit()"
                        >
                    <% end %>
                    
                    <p class='<%= todo.completed ? "TodoItem-text-checked" : ""%>'>
                        <%= todo.todo_text %>
                    </p>
                    <p class="date_display">
                        <% if date_display %>
                            <%= todo.due_date.to_s(:short) %>
                        <% end %>
                    </p>
                    <%= form_with(url: "/todos/#{todo.id}", method: "delete") do %>
                        <input 
                            class="TodoItem-delete"
                            type="image" 
                            src="trashcan.png"
                        >
                    <% end %>
                </label>
            </li>
        <% end %>
    </ul>
</section>

app/views/todos/index.html.erb
<head>
    <title>Todos List</title>
</head>
<body>
    <main class="TodoPageMain">
        <h1 class="TodoTitle">My To-Do List</h1>
        <section>
            <div class="AddNewTodo">
                <%= form_with(url: "/todos", method: "post") do %> 
                    <input class="InputText" type="text" name="todo_text_input" placeholder="What's new?">
                    <input class="InputDate" type="date" name="due_date_input">
                    <button class="AddButton" type="submit">Add</button>
                <% end %>
            </div>
        </section>

        <%= render partial: "todo-section", locals: {
            section_title: "Overdue",
            todos: @todos.overdue,
            date_display: true
        } %>
        <%= render partial: "todo-section", locals: {
            section_title: "Due Today",
            todos: @todos.duetoday,
            date_display: false
        } %>
        <%= render partial: "todo-section", locals: {
            section_title: "Due Later",
            todos: @todos.duelater,
            date_display: true
        } %>
        
    </main>
</body>

app/views/users/new.html.erb
<article class="UsersNew-main">
<p class="NewUsers-title">Welcome new user!</p>

<section class = "UsersNew">
    <%= form_with(url: users_path,method: "post") do |form| %>
        <div class = "Form-section">
            <p class="FormInput-label">First Name: </p>
            <%= form.text_field :first_name, class: "Form-input" %>
        </div>

        <div class = "Form-section">
            <p class="FormInput-label">Last Name: </p>
            <%= form.text_field :last_name, class: "Form-input" %>
        </div>
        
        <div class = "Form-section">
            <p class="FormInput-label">Email: </p>
            <%= form.email_field :email, class: "Form-input" %>
        </div>

        <div class = "Form-section">
            <p class="FormInput-label">Password: </p>
            <%= form.password_field :password, class: "Form-input" %>
        </div>

        <div class = "Form-section-submit">
            <%= form.submit "Sign Up!", class: "Form-submit" %>
            <%= link_to "Home", "/" %>
        </div>
    <% end %>
</section>
</article>